# Cop supports --auto-correct.
# Configuration parameters: AutoCorrect, EnforcedStyle.
# SupportedStyles: nested, compact
Style/ClassAndModuleChildren:
  EnforcedStyle: compact

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: require_parentheses, require_no_parentheses, require_no_parentheses_except_multiline
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

# Cop supports --auto-correct.
Style/RedundantSelf:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
